### ISSUE TITLE
New T-Display-S3 AMOLED version

### ISSUE THREAD

**Issue by hapklaar** [landonr/lilygo-tdisplays3-esphome#25]
I just got [this new board](https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED), which seems to be a variant of the original T-Display-S3 version. It has an AMOLED screen with a higher resolution (240*536)

Would it be possible to add support for this board in your code?

**Comment by guillempages** [comment]
Without having the hardware myself it's difficult to say ;-) Especially without the possibility of debugging.

Could you try just using the normal t-display-s3 and specifying the resolution manually? 
```
display:
   platform: tdisplays3
   width: 240
   height: 536
   #...
```
I don't think it is *that* easy, but it's worth a shot

**Comment by hapklaar** [comment]
Unfortunately didn't work :(

Screen stays black and a green led is on below the bottom right button. Looks like addressing is different on this one.

**Comment by hapklaar** [comment]
Upon second try, it actually flashed correctly and booten, but nothing on display. It seems this device is using a totally different [display controller](https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/blob/main/datasheet/RM67162%20DataSheet_V0.0.pdf)

**Comment by landonr** [comment]
It doesn't seem too difficult to set this up if we follow the example code https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/blob/main/examples/TFT_eSPI_Sprite/rm67162.h
I'll look into buying one of these tdisplays, they're really nice

**Comment by hapklaar** [comment]
> I'll look into buying one of these tdisplays, they're really nice

That's cool. Let me do a small contribution to the cause ;)

**Comment by landonr** [comment]
Thank you very much! @guillempages have you looked into an amoled s3? If you havent

**Comment by guillempages** [comment]
No, I haven't.

**Comment by julianrinaldi** [comment]
I would also love support for this version. I bought a few not realizing it was a newer unsupported model. But it's probably going to be my favorite ESPHome device once it's possible to use it.

**Comment by bluechris** [comment]
Yeah i also got the devide here and in the life of me i cannot make the screen to light up with Esphome...

**Comment by landonr** [comment]
can you check if your boards are set up for spi or qspi? 
![image](https://github.com/landonr/lilygo-tdisplays3-esphome/assets/2607659/2877e21f-499f-4654-b8c1-6edf9cf3f69a)

if its qspi then I think we need to include this `rm67162.h` file and call init like this
`rm67162_init();`

https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/blob/eec58359ca665510dcd0bdae5d0b78a7fc383a34/examples/TFT_eSPI_Sprite/TFT_eSPI_Sprite.ino#L39C20-L39C20

**Comment by julianrinaldi** [comment]
It looks like QSPI.

**Comment by hapklaar** [comment]
Can confirm, board looks identical to the left pic with the zero ohm resistors on QSPI

**Comment by hapklaar** [comment]
Curious if anyone was able to make some progress on this?

**Comment by guillempages** [comment]
I haven't, and AFAIK @landonr hasn't either. 
BUT
@clydebarrow has a branch on his esphome fork that actually has support for that device. He has posted his configuration on discord, so I'm pasting the relevant parts here, in case you want to try:
```
esphome:
  name: t-amoled
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

external_components:
  - source: github://clydebarrow/esphome@amoled
    components: [ spi, qspi_amoled]

spi:
  - id: quad_spi
    clk_pin: 47
    data_pins:
      - 18
      - 7
      - 48
      - 5
display:
  - platform: qspi_amoled
    dimensions:
      height: 240
      width: 536
      offset_height: 0
      offset_width: 0
    transform:
      mirror_x: false
      mirror_y: true
      swap_xy: true
    color_order: rgb
    invert_colors: false
    brightness: 255
    cs_pin: 6
    reset_pin: 17
    enable_pin: 38
    lambda: |-

psram:
  mode: octal
```
