### ISSUE TITLE
my previously working project fails to compile with fatal error: User_Setup_Select.h: No such file or directory

### ISSUE THREAD

**Issue by spitfire** [landonr/lilygo-tdisplays3-esphome#41]
My previously working project fails to compile with:
```
In file included from src/esphome/components/tdisplays3/t_display_s3.h:4,
                 from src/esphome/components/tdisplays3/t_display_s3.cpp:1:
.piolibdeps/t-display-s3-01/TFT_eSPI/TFT_eSPI.h:69:10: fatal error: User_Setup_Select.h: No such file or directory
```

is this related to https://github.com/landonr/lilygo-tdisplays3-esphome/pull/40 ?

**Comment by landonr** [comment]
definitely related. you can revert for now by updating the component to this

```
  - source: 
      type: git
      url: https://github.com/landonr/lilygo-tdisplays3-esphome/
      ref: sept2023
    components: [tdisplays3]
```
