### ISSUE TITLE
Failed config with esphome 2023.11.x

### ISSUE THREAD

**Issue by WarC0zes** [landonr/lilygo-tdisplays3-esphome#42]
Hi,
I just updated ESPhome to version 2023.11.2. (I was in version 2023.10.6).
I wanted to update the firmware, but I received this error:
```
INFO ESPHome 2023.11.2
INFO Reading configuration /config/esphome/s3-display.yaml...
Failed config

esp32: None
  
  Please specify flash_size within esp32 configuration only.
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework: 
    version: 2.0.5
    source: ~3.20005.0
    platform_version: platformio/espressif32@5.4.0
    type: arduino
  flash_size: 4MB
```
![config fail](https://github.com/landonr/lilygo-tdisplays3-esphome/assets/91471397/0d6e4480-4e6b-47ab-ad56-1ef8a8c38e55)

from what I understand, you have to pass the **platformio option:** for flash_size to **esp32:**

How to modify it?
```
esphome:
  name: s3-display
  friendly_name: ESP32-S3 T-Display
  platformio_options:
    board_build.f_flash: 80000000L
    board_upload.flash_size: 16MB
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi

external_components:
  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
```

**Comment by WarC0zes** [comment]
like that, it works.
```
esphome:
  name: s3-display
  friendly_name: ESP32-S3 T-Display
  platformio_options:
    board_build.f_flash: 80000000L
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi

external_components:
  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
  flash_size: 16MB
```
