### ISSUE TITLE
Dimmable?

### ISSUE THREAD

**Issue by dalanmiller** [landonr/lilygo-tdisplays3-esphome#64]
Hi there 🙋🏻‍♂️, 

I don't quite understand this bit in the example yaml. 

```
output:
  - platform: ledc
    pin: GPIO38
    id: gpio38
    frequency: 2000

light:
  - platform: monochromatic
    output: gpio38
    name: "Backlight"
    restore_mode: RESTORE_DEFAULT_ON

# You can either setup the backlight as a switch like below or make it dimmable using a light output like above
# switch:
#   - platform: gpio
#     pin: GPIO38
#     name: "Backlight"
#     id: backlight
#     internal: true
#     restore_mode: RESTORE_DEFAULT_ON
```

How does this make the display dimmable? I can't seem to alter the display brightness whatsoever and I'm trying to lower the power consumption. 

This sources imply that it is both configurable and others have found success in doing so:

https://esphome.io/components/output/ledc.html
https://github.com/Xinyuan-LilyGO/T-Display-S3/issues/74

But I don't see how to replicate the raw Arduino code mentioned below in esphome? 

https://github.com/Xinyuan-LilyGO/T-Display-S3/issues/74#issuecomment-1366378638
